# 1. Local CSV

In [1]:
import pandas as pd
df = pd.read_csv("../Data/Football_Player_Stats.csv")
df

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
0,1,Max Aarons,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
1,2,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
2,3,Salis Abdul Samed,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
3,4,Laurent Abergel,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
4,5,Charles Abi,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Federico Ceccherini,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
496,497,Emil Ceide,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
497,498,Zeki Çelik,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
498,499,Fabien Centonze,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
499,500,Luca Ceppitelli,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

# 2. TSV Data

In [2]:
tsv_df = pd.read_csv("../Data/movie_titles_metadata.tsv", sep="\t")
tsv_df

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756,['action' 'adventure' 'romance' 'sci-fi' 'thri...
5,m6,8mm,1999,6.3,48212,['crime' 'mystery' 'thriller']
6,m7,a nightmare on elm street 4: the dream master,1988,5.2,13590,['fantasy' 'horror' 'thriller']
7,m8,a nightmare on elm street: the dream child,1989,4.7,11092,['fantasy' 'horror' 'thriller']
8,m9,the atomic submarine,1959,4.9,513,['sci-fi' 'thriller']
9,m10,affliction,1997,6.9,7252,['drama' 'mystery' 'thriller']
10,m11,air force one,1997,6.3,61978,['action' 'drama' 'thriller']
11,m12,airplane ii: the sequel,1982,5.8,15210,['comedy' 'romance' 'sci-fi']
12,m13,airplane!,1980,7.8,57692,['comedy' 'romance']
13,m14,alien nation,1988,6.1,5590,['crime' 'drama' 'sci-fi' 'thriller']
14,m15,aliens,1986,8.5,173518,['action' 'sci-fi' 'thriller']
15,m16,amadeus,1984,8.4,99138,['biography' 'drama' 'music']
16,m17,an american werewolf in london,1981,7.5,24443,['horror' 'romance']
17,m18,american madness,1932,7.4,702,['drama']
18,m19,american outlaws,2001,5.7,7425,['action' 'western']

# 3. Make title

In [3]:
tsv_df = pd.read_csv("../Data/movie_titles_metadata.tsv", sep="\t",names=['m',"Movie",'Year',"rating",'Vote','Genre'])
tsv_df

,m,Movie,Year,rating,Vote,Genre
0,m0,10 things i hate about you,1999,6.9,62847,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289,['action' 'comedy' 'crime' 'drama' 'thriller']
5,m5,the fifth element,1997,7.5,133756,['action' 'adventure' 'romance' 'sci-fi' 'thri...
6,m6,8mm,1999,6.3,48212,['crime' 'mystery' 'thriller']
7,m7,a nightmare on elm street 4: the dream master,1988,5.2,13590,['fantasy' 'horror' 'thriller']
8,m8,a nightmare on elm street: the dream child,1989,4.7,11092,['fantasy' 'horror' 'thriller']
9,m9,the atomic submarine,1959,4.9,513,['sci-fi' 'thriller']
10,m10,affliction,1997,6.9,7252,['drama' 'mystery' 'thriller']
11,m11,air force one,1997,6.3,61978,['action' 'drama' 'thriller']
12,m12,airplane ii: the sequel,1982,5.8,15210,['comedy' 'romance' 'sci-fi']
13,m13,airplane!,1980,7.8,57692,['comedy' 'romance']
14,m14,alien nation,1988,6.1,5590,['crime' 'drama' 'sci-fi' 'thriller']
15,m15,aliens,1986,8.5,173518,['action' 'sci-fi' 'thriller']
16,m16,amadeus,1984,8.4,99138,['biography' 'drama' 'music']
17,m17,an american werewolf in london,1981,7.5,24443,['horror' 'romance']
18,m18,american madness,1932,7.4,702,['drama']
19,m19,american outlaws,2001,5.7,7425,['action' 'western']

# 4. Make a col as index

In [4]:
df = pd.read_csv("../Data/Football_Player_Stats.csv", index_col=["Player"])
df

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

# 5. First data as column

In [5]:
df = pd.read_csv("../Data/test.csv", header=1)
df

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

# 6. Selective Column

In [6]:
df = pd.read_csv("../Data/Football_Player_Stats.csv",usecols=['Player','Pos','Squad'])
df

                  Player   Pos          Squad
0             Max Aarons    DF   Norwich City
1       Yunis Abdelhamid    DF          Reims
2      Salis Abdul Samed    MF  Clermont Foot
3        Laurent Abergel    MF        Lorient
4            Charles Abi    FW  Saint-Étienne
..                   ...   ...            ...
495  Federico Ceccherini    DF  Hellas Verona
496           Emil Ceide  FWDF       Sassuolo
497           Zeki Çelik    DF          Lille
498      Fabien Centonze    DF           Metz
499      Luca Ceppitelli    DF       Cagliari

[500 rows x 3 columns]

# 7. Skip Row

In [8]:
df = pd.read_csv("../Data/Football_Player_Stats.csv",skiprows=[1,2,3])
df

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
0,4,Laurent Abergel,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
1,5,Charles Abi,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,6,Dickson Abiama,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,0.37,0.00,0.00,0.00,2.22,0.49,0.12
3,7,Matthis Abline,FRA,FW,Rennes,Ligue 1,19,2003,7,0.00,0.00,0.00,0.00,1.82,0.00,0.00
4,8,Tammy Abraham,ENG,FW,Roma,Serie A,24,1997,37,0.26,0.00,0.00,0.50,2.71,0.93,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,496,Federico Ceccherini,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
493,497,Emil Ceide,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
494,498,Zeki Çelik,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
495,499,Fabien Centonze,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
496,500,Luca Ceppitelli,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

# 8. Encoding

In [9]:
df = pd.read_csv('../Data/zomato.csv',encoding='latin-1')
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591