In [1]:
import pandas as pd

In [2]:
student_data = [
    ['Jehan',80,21],
    ['Hasan',99,52],
    ['Adib',56,21]
]
pd.DataFrame(student_data, columns=["Name","Marks","Age"])

    Name  Marks  Age
0  Jehan     80   21
1  Hasan     99   52
2   Adib     56   21

# From Dictionary

In [3]:
student_data = {
    'Name' : ['Jehan', 'Hasan', 'Adib'],
    'Marks' : [80, 99, 56],
    'Age' : [21, 52, 21]
}
pd.DataFrame(student_data)

    Name  Marks  Age
0  Jehan     80   21
1  Hasan     99   52
2   Adib     56   21

# From CSV

In [4]:
df = pd.read_csv("../../Data/Football_Player_Stats.csv", index_col="Player")
df

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

# Dataframe attribute

In [5]:
df.shape

(500, 15)

In [6]:
df.dtypes

Rk           int64
Nation         str
Pos            str
Squad          str
Comp           str
Age          int64
Born         int64
MP           int64
CrdY       float64
CrdR       float64
2CrdY      float64
Goals      float64
Shots      float64
SoT        float64
Assists    float64
dtype: object

In [7]:
df.index

Index(['Max Aarons', 'Yunis Abdelhamid', 'Salis Abdul Samed',
       'Laurent Abergel', 'Charles Abi', 'Dickson Abiama', 'Matthis Abline',
       'Tammy Abraham', 'Luis Abram', 'Francesco Acerbi',
       ...
       'Catena', 'Craig Cathcart', 'Edinson Cavani', 'Dani Ceballos',
       'Pietro Ceccaroni', 'Federico Ceccherini', 'Emil Ceide', 'Zeki Çelik',
       'Fabien Centonze', 'Luca Ceppitelli'],
      dtype='str', name='Player', length=500)

In [8]:
df.columns

Index(['Rk', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', 'MP', 'CrdY',
       'CrdR', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists'],
      dtype='str')

In [9]:
df.values

array([[1, 'ENG', 'DF', ..., 0.41, 0.06, 0.06],
       [2, 'MAR', 'DF', ..., 0.54, 0.18, 0.0],
       [3, 'GHA', 'MF', ..., 0.66, 0.18, 0.0],
       ...,
       [498, 'TUR', 'DF', ..., 0.77, 0.1, 0.1],
       [499, 'FRA', 'DF', ..., 0.85, 0.4, 0.06],
       [500, 'ITA', 'DF', ..., 0.43, 0.06, 0.06]],
      shape=(500, 15), dtype=object)

In [10]:
type(df.values)

numpy.ndarray

In [11]:
df.head()

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [12]:
df.tail()

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06

In [13]:
df.sample(5)

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Harrison Ashby,133,SCO,DF,West Ham,Premier League,20,2001,1,0.00,0.0,0.0,0.00,0.00,0.00,0.00
Taiwo Awoniyi,149,NGA,FW,Union Berlin,Bundesliga,24,1997,31,0.04,0.0,0.0,0.62,2.73,1.24,0.04
Daniele Baselli,219,ITA,MFFW,Torino,Serie A,30,1992,6,0.00,0.0,0.0,0.00,0.59,0.00,0.00
Matty Cash,479,POL,DF,Aston Villa,Premier League,24,1997,38,0.21,0.0,0.0,0.11,0.96,0.35,0.08
Amath,81,SEN,FWMF,Mallorca,La Liga,25,1996,19,0.51,0.0,0.0,0.00,1.12,0.41,0.10

### Summary info

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 500 entries, Max Aarons to Luca Ceppitelli
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk       500 non-null    int64
 1   Nation   500 non-null    str
 2   Pos      500 non-null    str
 3   Squad    500 non-null    str
 4   Comp     500 non-null    str
 5   Age      500 non-null    int64
 6   Born     500 non-null    int64
 7   MP       500 non-null    int64
 8   CrdY     500 non-null    float64
 9   CrdR     500 non-null    float64
 10  2CrdY    500 non-null    float64
 11  Goals    500 non-null    float64
 12  Shots    500 non-null    float64
 13  SoT      500 non-null    float64
 14  Assists  500 non-null    float64
dtypes: float64(7), int64(4), str(4)
memory usage: 62.5+ KB

In [15]:
df.describe()

,Rk,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
count,500.000000,500.0000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,250.500000,26.0840,1995.428000,18.842000,0.200180,0.007100,0.003320,0.109280,1.202860,0.393340,0.088220
std,144.481833,4.6661,4.651461,11.770051,0.226039,0.026744,0.019113,0.228774,1.430507,0.674536,0.257428
min,1.000000,16.0000,1981.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,125.750000,22.7500,1992.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.290000,0.000000,0.000000
50%,250.500000,26.0000,1996.000000,19.000000,0.160000,0.000000,0.000000,0.000000,0.770000,0.190000,0.000000
75%,375.250000,30.0000,1999.000000,30.000000,0.290000,0.000000,0.000000,0.132500,1.822500,0.565000,0.112500
max,500.000000,40.0000,2005.000000,38.000000,1.670000,0.230000,0.220000,3.330000,15.000000,10.000000,5.000000

### null

In [16]:
titanic_toy = pd.read_csv("../../Data/titanic_toy.csv")
titanic_toy

      Age     Fare  Family  Survived
0    22.0   7.2500       1         0
1    38.0  71.2833       1         1
2    26.0   7.9250       0         1
3    35.0  53.1000       1         1
4    35.0   8.0500       0         0
..    ...      ...     ...       ...
886  27.0  13.0000       0         0
887  19.0  30.0000       0         1
888   NaN  23.4500       3         0
889  26.0      NaN       0         1
890  32.0   7.7500       0         0

[891 rows x 4 columns]

In [17]:
titanic_toy.isnull()

       Age   Fare  Family  Survived
0    False  False   False     False
1    False  False   False     False
2    False  False   False     False
3    False  False   False     False
4    False  False   False     False
..     ...    ...     ...       ...
886  False  False   False     False
887  False  False   False     False
888   True  False   False     False
889  False   True   False     False
890  False  False   False     False

[891 rows x 4 columns]

In [18]:
titanic_toy.isnull().sum()

Age         177
Fare         45
Family        0
Survived      0
dtype: int64

In [19]:
titanic_toy.isnull().mean() * 100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [20]:
titanic_toy.duplicated().sum()

np.int64(129)

In [21]:
titanic_toy.rename(columns={"Family":"Family Member"})

      Age     Fare  Family Member  Survived
0    22.0   7.2500              1         0
1    38.0  71.2833              1         1
2    26.0   7.9250              0         1
3    35.0  53.1000              1         1
4    35.0   8.0500              0         0
..    ...      ...            ...       ...
886  27.0  13.0000              0         0
887  19.0  30.0000              0         1
888   NaN  23.4500              3         0
889  26.0      NaN              0         1
890  32.0   7.7500              0         0

[891 rows x 4 columns]

# Math method

In [22]:
df[['MP', 'CrdY','CrdR', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists']].sum()

MP         9421.00
CrdY        100.09
CrdR          3.55
2CrdY         1.66
Goals        54.64
Shots       601.43
SoT         196.67
Assists      44.11
dtype: float64

In [23]:
df[['MP', 'CrdY','CrdR', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists']].mean()

MP         18.84200
CrdY        0.20018
CrdR        0.00710
2CrdY       0.00332
Goals       0.10928
Shots       1.20286
SoT         0.39334
Assists     0.08822
dtype: float64

In [24]:
df[['MP', 'CrdY','CrdR', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists']].var()

MP         138.534104
CrdY         0.051094
CrdR         0.000715
2CrdY        0.000365
Goals        0.052337
Shots        2.046352
SoT          0.454999
Assists      0.066269
dtype: float64

# Select Columns

In [25]:
df['MP']

Player
Max Aarons             34
Yunis Abdelhamid       34
Salis Abdul Samed      31
Laurent Abergel        34
Charles Abi             1
                       ..
Federico Ceccherini    34
Emil Ceide              6
Zeki Çelik             32
Fabien Centonze        19
Luca Ceppitelli        24
Name: MP, Length: 500, dtype: int64

In [26]:
df[['MP', 'CrdY','CrdR', '2CrdY', 'Goals', 'Shots', 'SoT', 'Assists']]

                     MP  CrdY  CrdR  2CrdY  Goals  Shots   SoT  Assists
Player
Max Aarons           34  0.25  0.00   0.00   0.00   0.41  0.06     0.06
Yunis Abdelhamid     34  0.15  0.03   0.00   0.06   0.54  0.18     0.00
Salis Abdul Samed    31  0.44  0.11   0.07   0.04   0.66  0.18     0.00
Laurent Abergel      34  0.27  0.00   0.00   0.00   0.91  0.21     0.06
Charles Abi           1  0.00  0.00   0.00   0.00   0.00  0.00     0.00
...                  ..   ...   ...    ...    ...    ...   ...      ...
Federico Ceccherini  34  0.46  0.04   0.04   0.04   0.42  0.08     0.00
Emil Ceide            6  0.00  0.00   0.00   0.00   0.00  0.00     0.00
Zeki Çelik           32  0.33  0.00   0.00   0.07   0.77  0.10     0.10
Fabien Centonze      19  0.17  0.00   0.00   0.23   0.85  0.40     0.06
Luca Ceppitelli      24  0.19  0.00   0.00   0.06   0.43  0.06     0.06

[500 rows x 8 columns]

# Select Row

In [27]:
df.iloc[5]

Rk                      6
Nation                NGA
Pos                    FW
Squad      Greuther Fürth
Comp           Bundesliga
Age                    23
Born                 1998
MP                     24
CrdY                 0.37
CrdR                  0.0
2CrdY                 0.0
Goals                 0.0
Shots                2.22
SoT                  0.49
Assists              0.12
Name: Dickson Abiama, dtype: object

In [28]:
df.iloc[3:5]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.0,0.0,0.0,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.0,0.0,0.0,0.00,0.00,0.00

In [29]:
df.iloc[[3,5,8]]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.0,0.0,0.0,0.91,0.21,0.06
Dickson Abiama,6,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,0.37,0.0,0.0,0.0,2.22,0.49,0.12
Luis Abram,9,PER,DF,Granada,La Liga,26,1996,8,0.32,0.0,0.0,0.0,0.32,0.00,0.00

In [30]:
# using loc
df.loc['Laurent Abergel']

Rk               4
Nation         FRA
Pos             MF
Squad      Lorient
Comp       Ligue 1
Age             29
Born          1993
MP              34
CrdY          0.27
CrdR           0.0
2CrdY          0.0
Goals          0.0
Shots         0.91
SoT           0.21
Assists       0.06
Name: Laurent Abergel, dtype: object

In [31]:
df.loc['Laurent Abergel' : 'Luis Abram']

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.0,0.0,0.0,0.91,0.21,0.06
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.0,0.0,0.0,0.00,0.00,0.00
Dickson Abiama,6,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,0.37,0.0,0.0,0.0,2.22,0.49,0.12
Matthis Abline,7,FRA,FW,Rennes,Ligue 1,19,2003,7,0.00,0.0,0.0,0.0,1.82,0.00,0.00
Tammy Abraham,8,ENG,FW,Roma,Serie A,24,1997,37,0.26,0.0,0.0,0.5,2.71,0.93,0.12
Luis Abram,9,PER,DF,Granada,La Liga,26,1996,8,0.32,0.0,0.0,0.0,0.32,0.00,0.00

In [32]:
df.loc[['Laurent Abergel' ,'Dickson Abiama', 'Luis Abram']]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.0,0.0,0.0,0.91,0.21,0.06
Dickson Abiama,6,NGA,FW,Greuther Fürth,Bundesliga,23,1998,24,0.37,0.0,0.0,0.0,2.22,0.49,0.12
Luis Abram,9,PER,DF,Granada,La Liga,26,1996,8,0.32,0.0,0.0,0.0,0.32,0.00,0.00

# Select row and cols

In [33]:
df.iloc[2:5, 5:9]

                   Age  Born  MP  CrdY
Player
Salis Abdul Samed   22  2000  31  0.44
Laurent Abergel     29  1993  34  0.27
Charles Abi         22  2000   1  0.00

In [34]:
df['Age'] > 30

Player
Max Aarons             False
Yunis Abdelhamid        True
Salis Abdul Samed      False
Laurent Abergel        False
Charles Abi            False
                       ...
Federico Ceccherini    False
Emil Ceide             False
Zeki Çelik             False
Fabien Centonze        False
Luca Ceppitelli         True
Name: Age, Length: 500, dtype: bool

In [35]:
df[df['Age'] > 30]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.0,0.06,0.54,0.18,0.00
Francesco Acerbi,10,ITA,DF,Lazio,Serie A,34,1988,30,0.07,0.04,0.0,0.14,0.57,0.25,0.00
Sergio Agüero,27,ARG,FW,Barcelona,La Liga,33,1988,4,0.00,0.00,0.0,0.59,3.53,0.59,0.00
Jordi Alba,51,ESP,DF,Barcelona,La Liga,33,1989,30,0.37,0.00,0.0,0.07,1.05,0.20,0.34
Raúl Albiol,54,ESP,DF,Villarreal,La Liga,36,1985,28,0.29,0.00,0.0,0.00,0.22,0.04,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kiko Casilla,480,ESP,GK,Elche,La Liga,35,1986,14,0.21,0.00,0.0,0.00,0.00,0.00,0.00
Gonzalo Castro,487,GER,MFFW,Arminia,Bundesliga,34,1987,12,0.00,0.00,0.0,0.21,1.67,0.42,0.21
Craig Cathcart,492,NIR,DF,Watford,Premier League,33,1989,31,0.11,0.00,0.0,0.00,0.11,0.00,0.04
Edinson Cavani,493,URU,FW,Manchester Utd,Premier League,35,1987,15,0.00,0.00,0.0,0.24,2.12,0.71,0.12
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.0,0.06,0.43,0.06,0.06

In [36]:
df[(df['Age'] > 30) & (df['Pos'] == 'DF')]

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists
Player,,,,,,,,,,,,,,,
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.0,0.06,0.54,0.18,0.00
Francesco Acerbi,10,ITA,DF,Lazio,Serie A,34,1988,30,0.07,0.04,0.0,0.14,0.57,0.25,0.00
Jordi Alba,51,ESP,DF,Barcelona,La Liga,33,1989,30,0.37,0.00,0.0,0.07,1.05,0.20,0.34
Raúl Albiol,54,ESP,DF,Villarreal,La Liga,36,1985,28,0.29,0.00,0.0,0.00,0.22,0.04,0.00
Marcos Alonso,72,ESP,DF,Chelsea,Premier League,31,1990,28,0.33,0.00,0.0,0.17,1.78,0.41,0.17
Dani Alves,76,BRA,DF,Barcelona,La Liga,39,1983,14,0.16,0.08,0.0,0.08,0.41,0.16,0.25
José Ángel,98,ESP,DF,Osasuna,La Liga,32,1989,23,0.17,0.08,0.0,0.08,0.92,0.25,0.08
Cristian Ansaldi,101,ARG,DF,Torino,Serie A,35,1986,19,0.26,0.00,0.0,0.00,0.91,0.13,0.39
Ramzi Aya,150,ITA,DF,Salernitana,Serie A,31,1990,2,0.67,0.00,0.0,0.00,0.67,0.00,0.00
Karim Azamoum,154,FRA,DF,Troyes,Ligue 1,32,1990,7,0.47,0.00,0.0,0.00,0.70,0.70,0.00
César Azpilicueta,156,ESP,DF,Chelsea,Premier League,32,1989,27,0.13,0.00,0.0,0.04,0.57,0.17,0.09
Mikel Balenziaga,185,ESP,DF,Athletic Club,La Liga,34,1988,26,0.09,0.00,0.0,0.00,0.27,0.09,0.00
Abdoulaye Bamba,190,CIV,DF,Angers,Ligue 1,32,1990,10,0.20,0.00,0.0,0.00,0.20,0.00,0.00
Antonio Barragán,212,ESP,DF,Elche,La Liga,34,1987,16,0.44,0.00,0.0,0.00,0.09,0.00,0.00
Marc Bartra,218,ESP,DF,Betis,La Liga,31,1991,23,0.23,0.00,0.0,0.05,0.68,0.14,0.00
Paul Baysse,236,FRA,DF,Bordeaux,Ligue 1,34,1988,2,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Yuri Berchiche,288,ESP,DF,Athletic Club,La Liga,32,1990,14,0.27,0.00,0.0,0.09,0.71,0.27,0.18
Ryan Bertrand,304,ENG,DF,Leicester City,Premier League,32,1989,4,0.27,0.00,0.0,0.00,0.00,0.00,0.00
Ermin Bi?ak?i?,310,BIH,DF,Hoffenheim,Bundesliga,32,1990,1,0.00,0.00,0.0,0.00,0.00,0.00,0.00
Pedro Bigas,312,ESP,DF,Elche,La Liga,31,1990,19,0.35,0.00,0.0,0.06,0.70,0.17,0.00
Jérôme Boateng,327,GER,DF,Lyon,Ligue 1,33,1988,24,0.33,0.00,0.0,0.00,0.28,0.17,0.06
Willy Boly,338,CIV,DF,Wolves,Premier League,31,1991,10,0.10,0.00,0.0,0.00,0.20,0.10,0.00
Leonardo Bonucci,344,ITA,DF,Juventus,Serie A,35,1987,24,0.04,0.00,0.0,0.22,0.63,0.13,0.00
Dedryck Boyata,360,BEL,DF,Hertha BSC,Bundesliga,31,1990,23,0.05,0.05,0.0,0.00,0.47,0.09,0.00
Daniel Brosinski,382,GER,DF,Mainz 05,Bundesliga,33,1988,11,0.00,0.00,0.0,0.00,0.23,0.00,0.00
Martín Cáceres,417,URU,DF,Cagliari,Serie A,35,1987,14,0.33,0.11,0.0,0.11,0.76,0.11,0.11
Martín Cáceres,418,URU,DF,Levante,La Liga,35,1987,10,0.27,0.00,0.0,0.00,0.00,0.00,0.00
Cala,427,ESP,DF,Cádiz,La Liga,32,1989,14,0.76,0.10,0.1,0.00,0.48,0.00,0.00
Craig Cathcart,492,NIR,DF,Watford,Premier League,33,1989,31,0.11,0.00,0.0,0.00,0.11,0.00,0.04
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.0,0.06,0.43,0.06,0.06

In [37]:
titanic_toy.notnull()

       Age   Fare  Family  Survived
0     True   True    True      True
1     True   True    True      True
2     True   True    True      True
3     True   True    True      True
4     True   True    True      True
..     ...    ...     ...       ...
886   True   True    True      True
887   True   True    True      True
888  False   True    True      True
889   True  False    True      True
890   True   True    True      True

[891 rows x 4 columns]

In [38]:
titanic_toy[ titanic_toy.notnull() ]

      Age     Fare  Family  Survived
0    22.0   7.2500       1         0
1    38.0  71.2833       1         1
2    26.0   7.9250       0         1
3    35.0  53.1000       1         1
4    35.0   8.0500       0         0
..    ...      ...     ...       ...
886  27.0  13.0000       0         0
887  19.0  30.0000       0         1
888   NaN  23.4500       3         0
889  26.0      NaN       0         1
890  32.0   7.7500       0         0

[891 rows x 4 columns]

# Adding new col

In [39]:
df["Is player"] = True
df

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists,Is player
Player,,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True

# Remove null value

In [40]:
titanic_toy.dropna(inplace=True)
titanic_toy.info()

<class 'pandas.DataFrame'>
Index: 675 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       675 non-null    float64
 1   Fare      675 non-null    float64
 2   Family    675 non-null    int64
 3   Survived  675 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 26.4 KB

# change attribute type

In [42]:
df["SoT"] = df["SoT"].astype("float32")
df.info()

<class 'pandas.DataFrame'>
Index: 500 entries, Max Aarons to Luca Ceppitelli
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Rk         500 non-null    int64
 1   Nation     500 non-null    str
 2   Pos        500 non-null    str
 3   Squad      500 non-null    str
 4   Comp       500 non-null    str
 5   Age        500 non-null    int64
 6   Born       500 non-null    int64
 7   MP         500 non-null    int64
 8   CrdY       500 non-null    float64
 9   CrdR       500 non-null    float64
 10  2CrdY      500 non-null    float64
 11  Goals      500 non-null    float64
 12  Shots      500 non-null    float64
 13  SoT        500 non-null    float32
 14  Assists    500 non-null    float64
 15  Is player  500 non-null    bool
dtypes: bool(1), float32(1), float64(6), int64(4), str(4)
memory usage: 77.2+ KB

# Some Function

In [49]:
df.value_counts()

Rk   Nation  Pos   Squad          Comp            Age  Born  MP  CrdY  CrdR  2CrdY  Goals  Shots  SoT   Assists  Is player
1    ENG     DF    Norwich City   Premier League  22   2000  34  0.25  0.00  0.00   0.00   0.41   0.06  0.06     True         1
2    MAR     DF    Reims          Ligue 1         34   1987  34  0.15  0.03  0.00   0.06   0.54   0.18  0.00     True         1
3    GHA     MF    Clermont Foot  Ligue 1         22   2000  31  0.44  0.11  0.07   0.04   0.66   0.18  0.00     True         1
4    FRA     MF    Lorient        Ligue 1         29   1993  34  0.27  0.00  0.00   0.00   0.91   0.21  0.06     True         1
5    FRA     FW    Saint-Étienne  Ligue 1         22   2000  1   0.00  0.00  0.00   0.00   0.00   0.00  0.00     True         1
                                                                                                                             ..
496  ITA     DF    Hellas Verona  Serie A         30   1992  34  0.46  0.04  0.04   0.04   0.42   0.08  0.00     True         1
497  NOR     FWDF  Sassuolo       Serie A         20   2001  6   0.00  0.00  0.00   0.00   0.00   0.00  0.00     True         1
498  TUR     DF    Lille          Ligue 1         25   1997  32  0.33  0.00  0.00   0.07   0.77   0.10  0.10     True         1
499  FRA     DF    Metz           Ligue 1         26   1996  19  0.17  0.00  0.00   0.23   0.85   0.40  0.06     True         1
500  ITA     DF    Cagliari       Serie A         32   1989  24  0.19  0.00  0.00   0.06   0.43   0.06  0.06     True         1
Name: count, Length: 500, dtype: int64

In [50]:
df.sort_index()

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists,Is player
Player,,,,,,,,,,,,,,,,
Abdoulaye Bakayoko,175,FRA,DF,Saint-Étienne,Ligue 1,19,2002,4,0.00,0.0,0.0,0.00,0.00,0.00,0.00,True
Abdoulaye Bamba,190,CIV,DF,Angers,Ligue 1,32,1990,10,0.20,0.0,0.0,0.00,0.20,0.00,0.00,True
Abdourahmane Barry,217,FRA,DF,Greuther Fürth,Bundesliga,22,2000,8,0.87,0.0,0.0,0.00,0.43,0.00,0.00,True
Adam Armstrong,120,ENG,FW,Southampton,Premier League,25,1997,23,0.06,0.0,0.0,0.13,2.99,0.89,0.13,True
Adil Aouchiche,108,FRA,MFFW,Saint-Étienne,Ligue 1,19,2002,35,0.17,0.0,0.0,0.00,1.83,0.83,0.33,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Álex Cantero,455,ESP,FWMF,Levante,La Liga,21,2000,25,0.15,0.0,0.0,0.00,2.35,0.74,0.15,True
Álvaro Aguirre,29,ESP,FW,Rayo Vallecano,La Liga,22,2000,1,0.00,0.0,0.0,0.00,0.00,0.00,0.00,True
Álvaro Bastida,224,ESP,MF,Cádiz,La Liga,18,2004,6,0.45,0.0,0.0,0.00,0.00,0.00,0.00,True
Édgar Badía,162,ESP,GK,Elche,La Liga,30,1992,24,0.08,0.0,0.0,0.00,0.00,0.00,0.00,True
Étienne Capoue,460,FRA,MF,Villarreal,La Liga,33,1988,30,0.35,0.0,0.0,0.04,0.55,0.20,0.04,True

In [53]:
df

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists,Is player
Player,,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True

In [54]:
df = df.reset_index()
df

,Player,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists,Is player
0,Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True
1,Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True
2,Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True
3,Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True
4,Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True
496,Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
497,Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True
498,Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True
499,Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True

In [55]:
df.set_index("Player")

,Rk,Nation,Pos,Squad,Comp,Age,Born,MP,CrdY,CrdR,2CrdY,Goals,Shots,SoT,Assists,Is player
Player,,,,,,,,,,,,,,,,
Max Aarons,1,ENG,DF,Norwich City,Premier League,22,2000,34,0.25,0.00,0.00,0.00,0.41,0.06,0.06,True
Yunis Abdelhamid,2,MAR,DF,Reims,Ligue 1,34,1987,34,0.15,0.03,0.00,0.06,0.54,0.18,0.00,True
Salis Abdul Samed,3,GHA,MF,Clermont Foot,Ligue 1,22,2000,31,0.44,0.11,0.07,0.04,0.66,0.18,0.00,True
Laurent Abergel,4,FRA,MF,Lorient,Ligue 1,29,1993,34,0.27,0.00,0.00,0.00,0.91,0.21,0.06,True
Charles Abi,5,FRA,FW,Saint-Étienne,Ligue 1,22,2000,1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Federico Ceccherini,496,ITA,DF,Hellas Verona,Serie A,30,1992,34,0.46,0.04,0.04,0.04,0.42,0.08,0.00,True
Emil Ceide,497,NOR,FWDF,Sassuolo,Serie A,20,2001,6,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True
Zeki Çelik,498,TUR,DF,Lille,Ligue 1,25,1997,32,0.33,0.00,0.00,0.07,0.77,0.10,0.10,True
Fabien Centonze,499,FRA,DF,Metz,Ligue 1,26,1996,19,0.17,0.00,0.00,0.23,0.85,0.40,0.06,True
Luca Ceppitelli,500,ITA,DF,Cagliari,Serie A,32,1989,24,0.19,0.00,0.00,0.06,0.43,0.06,0.06,True